// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJhWTk8Dz1jX6nLUkXUHgGdQvAO4N_Q4I',
    appId: '1:1055292276867:web:04d047e8c3702a37799bb6',
    messagingSenderId: '1055292276867',
    projectId: 'tymos-169fd',
    authDomain: 'tymos-169fd.firebaseapp.com',
    storageBucket: 'tymos-169fd.firebasestorage.app',
    measurementId: 'G-KT65KV8B24',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4CIuhvWBh6_bJDIeeYY-I-c0WsSPOofA',
    appId: '1:1055292276867:android:f8f6330d87f98252799bb6',
    messagingSenderId: '1055292276867',
    projectId: 'tymos-169fd',
    storageBucket: 'tymos-169fd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAKhRIOk-oXI1mUkQ-GCrFKDTt4MhoBK-w',
    appId: '1:1055292276867:ios:fa5f81eb730647df799bb6',
    messagingSenderId: '1055292276867',
    projectId: 'tymos-169fd',
    storageBucket: 'tymos-169fd.firebasestorage.app',
    iosBundleId: 'com.example.flutterTymos',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAKhRIOk-oXI1mUkQ-GCrFKDTt4MhoBK-w',
    appId: '1:1055292276867:ios:fa5f81eb730647df799bb6',
    messagingSenderId: '1055292276867',
    projectId: 'tymos-169fd',
    storageBucket: 'tymos-169fd.firebasestorage.app',
    iosBundleId: 'com.example.flutterTymos',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAJhWTk8Dz1jX6nLUkXUHgGdQvAO4N_Q4I',
    appId: '1:1055292276867:web:eee0772d96129996799bb6',
    messagingSenderId: '1055292276867',
    projectId: 'tymos-169fd',
    authDomain: 'tymos-169fd.firebaseapp.com',
    storageBucket: 'tymos-169fd.firebasestorage.app',
    measurementId: 'G-BLCHNVQX25',
  );
}
